version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '9001:27017'
    volumes:
      - mongodb-data:/data/db
    networks:
      - mongodb-network

networks:
  mongodb-network:
    name: subscriptions-manager-mongodb-network

volumes:
  mongodb-data:
    name: subscriptions-manager-mongodb-data
