name: Install NPM dependencies

on: push

jobs:
  install-deps:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-

      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.0

      - run: npm ci
