name: Lint and test

on:
  workflow_run:
    workflows: [Install NPM dependencies]
    types: [completed]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Lint every apps and libs
        run: npm run lint:all

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Test every apps and libs
        run: npm run test:all
