name: Lint and test

on:
  workflow_run:
    workflows: [Install NPM dependencies]
    types: [completed]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.0
          cache: 'npm'
      # nx is not found when retrieving cache
      - name: Install dependencies
        run: npm ci
      - name: Lint every apps and libs
        run: npm run lint:all

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.0
          cache: 'npm'
      # nx is not found when retrieving cache
      - name: Install dependencies
        run: npm ci
      - name: Test every apps and libs
        run: npm run test:all
